application: overstat-1306
version: v1
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /api/.*
  script: _go_app
- url: /.*
  static_dir: static
